spring.application.name=resume-tailor
server.port=8086

spring.config.import=optional:classpath:secrets.properties
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

openai.api.url=https://api.openai.com/v1/chat/completions
openai.api.model=gpt-4o
